### ISSUE TITLE
WriteContinue TODO

### ISSUE THREAD

**Issue by aoiorio** [takuma-shishido/dejavu#19]
## 🍤Description
投稿を書く機能のTODOを消化するissueです！
#18 からやって来ました！
## 🍿TODO
- [ ] NovelMasterのstatusをNovelsに実装してしまっているのでNovelMasterに移動する
- [ ] 起承転結すべて終わった場合の処理がないため実装する
- [ ] デザインが最低限動作する状態のものになっているためデザインを追加する

**Comment by takuma-shishido** [comment]
プロジェクトが完成したため閉じます
